title: "svetisBlog"
description: "Self-Hosting, Smart Home, Netzwerk und Musikmachen – was bei mir läuft und wie es dahin gekommen ist"
author: "Svetlana"
baseurl: ""

encoding: utf-8
lang: de_DE
timezone: Europe/Berlin
url: "https://svetixoxo.github.io"

tagline: "Self-Hosting, Smart Home & Netzwerk"

# RSS-Feed
feed :
  path: feed.xml
  excerpt_only: false
  tags: true

# Markdown-Einstellungen
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:title/
timezone: Europe/Berlin

# Theme
theme: null

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - pages/themen.md
  - pages/archiv.md

# Ausschlüsse
exclude:
  - readMe.md
  - Gemfile
  - Gemfile.lock
